/*
**	Global variables header
**	Automatically generated by Emperor
*/

#ifndef __GLOBALS_H__
#define __GLOBALS_H__
/*
**	Function prototypes
*/

void OpenLibs( void );
void CleanExit(char *);

void AppRegistering( void );
void SavePrefsTree( void );

void InitLists( void );
void CleanupLists( void );

void FreeCommonList( struct List*,UBYTE );

void AppRegistering( void );
void SavePrefsTree( void );

void InitWindows( void );
void InitStuff( void );
void Events( void );
void ProcessMainMenus( UWORD, BOOL );


void Window1_CloseWindow_Evt(void);
void Ep_InitProgram(void);
void Ep_QuitProgram(void);

struct Screen *Ep_OpenScreen_Screen1(void);

void Ep_CloseScreen_Screen1(void);

struct Window *Ep_OpenWindow_Window1(void);

void Ep_CloseWindow_Window1(void);
void Menu_Information1_MenuPick_Evt(void);
void Menu_Quit1_MenuPick_Evt(void);

STRPTR inttostring(LONG);

/*
** My declarations
*/
void showmsg(char *textca);
int	 count;

struct IOStdReq * init_entropy ();
void free_entropy (struct IOStdReq * entropy);
int32 read_entropy (struct IOStdReq * entropy, char * dst, int32 len);

/*
**	Library&Interface declaration
*/

struct Library		*IntuitionBase;
struct Library		*LocaleBase;
struct Library		*GadToolsBase;
struct Library		*ASLBase;
struct Library		*DOSBase;
struct Library		*IconBase;
struct Library		*ResourceBase;
struct Library		*WindowBase;
struct Library		*RequesterBase;
struct Library		*ButtonBase;
struct Library		*CheckBoxBase;
struct Library		*ChooserBase;
struct Library		*ClickTabBase;
struct Library		*ColorWheelBase;
struct Library		*DateBrowserBase;
struct Library		*FuelGaugeBase;
struct Library		*GetFileBase;
struct Library		*GetFontBase;
struct Library		*GetScreenModeBase;
struct Library		*GradientSliderBase;
struct Library		*IntegerBase;
struct Library		*LayoutBase;
struct Library		*ListBrowserBase;
struct Library		*PaletteBase;
struct Library		*RadioButtonBase;
struct Library		*ScrollerBase;
struct Library		*SliderBase;
struct Library		*SpaceBase;
struct Library		*SpeedBarBase;
struct Library		*StringBase;
struct Library		*TapeDeckBase;
struct Library		*TextEditorBase;
struct Library		*BevelBase;
struct Library		*BitMapBase;
struct Library		*GlyphBase;
struct Library		*LabelBase;

struct IntuitionIFace		*IIntuition;
struct LocaleIFace		*ILocale;
struct GadToolsIFace		*IGadTools;
struct ASLIFace		*IASL;
struct DOSIFace		*IDOS;
struct IconIFace		*IIcon;
struct ResourceIFace		*IResource;
struct WindowIFace		*IWindow;
struct RequesterIFace		*IRequester;
struct ButtonIFace		*IButton;
struct CheckBoxIFace		*ICheckBox;
struct ChooserIFace		*IChooser;
struct ClickTabIFace		*IClickTab;
struct ColorWheelIFace		*IColorWheel;
struct DateBrowserIFace		*IDateBrowser;
struct FuelGaugeIFace		*IFuelGauge;
struct GetFileIFace		*IGetFile;
struct GetFontIFace		*IGetFont;
struct GetScreenModeIFace		*IGetScreenMode;
struct GradientSliderIFace		*IGradientSlider;
struct IntegerIFace		*IInteger;
struct LayoutIFace		*ILayout;
struct ListBrowserIFace		*IListBrowser;
struct PaletteIFace		*IPalette;
struct RadioButtonIFace		*IRadioButton;
struct ScrollerIFace		*IScroller;
struct SliderIFace		*ISlider;
struct SpaceIFace		*ISpace;
struct SpeedBarIFace		*ISpeedBar;
struct StringIFace		*IString;
struct TapeDeckIFace		*ITapeDeck;
struct TextEditorIFace		*ITextEditor;
struct BevelIFace		*IBevel;
struct BitMapIFace		*IBitMap;
struct GlyphIFace		*IGlyph;
struct LabelIFace		*ILabel;

enum
{
	LID_CHOOSER = 0,
	LID_CKTAB,
	LID_LBROWSE,
	LID_RBUTTON,
	LID_SPBAR
};

/*
**	Gadget&Objects Enumeration
*/

enum
{
	GID_Layout1 = 0,
	GID_Layout2,
	GID_Integer1,
	GID_Label1,
	GID_Space1,
	GID_Integer2,
	GID_Label2,
	GID_Space2,
	GID_Button1,
	GID_Layout3,
	GID_Texteditor1,
	GID_Scroller1,
	GID_LAST
};

enum
{
	OID_WindowObject1 = 0,
	OID_Inforequest1,
	OID_LAST
};

enum
{
	WID_Window1 = 0,
	WID_LAST
};
struct HintInfo	Hint_WindowObject1[1];

struct Screen		*Screen1;

void				*VisualInfo1;

struct Window		*win[WID_LAST];
Object			*obj[OID_LAST];
struct Gadget		*gad[GID_LAST];

struct MsgPort		*AppPort,
				*MsgPort;

struct NewMenu	Menu[4];
struct Menu		*Menustrip;
struct MenuItem	*item;

struct Catalog		*Catalog;
char Ep_ExtGadReturn[100];
#endif

