/*
**	system Structures stuff
**	Automatically generated by Emperor
*/


struct NewMenu Menu[] =
{
	{ NM_TITLE, 0, 0, 0, 0, 0 },
	{ NM_ITEM, 0, "I", 0, 0, 0 },
	{ NM_ITEM, 0, "Q", 0, 0, 0 },
	{ NM_END, 0, 0, 0, 0, 0 }
};

struct TagItem Ep_ModeIDtags_Screen1[] =
{
	{BIDTAG_Depth, 0},
	{BIDTAG_NominalWidth, 0},
	{BIDTAG_NominalHeight, 0},
};
struct HintInfo	Hint_WindowObject1[]=
{
	{-1,-1,NULL,0L}
};

const uint32 text_to_scroller[] = {
    GA_TEXTEDITOR_Prop_DeltaFactor,  SCROLLER_ArrowDelta,
    GA_TEXTEDITOR_Prop_Entries,      SCROLLER_Total,
    GA_TEXTEDITOR_Prop_First,	     SCROLLER_Top,
    GA_TEXTEDITOR_Prop_Visible,      SCROLLER_Visible,
    TAG_END};

const uint32 scroller_to_text[] = {
    SCROLLER_ArrowDelta,  GA_TEXTEDITOR_Prop_DeltaFactor,
    SCROLLER_Total,	  GA_TEXTEDITOR_Prop_Entries,
    SCROLLER_Top,	  GA_TEXTEDITOR_Prop_First,
    SCROLLER_Visible,	  GA_TEXTEDITOR_Prop_Visible,
    TAG_END};
