/*
**	Includes and definitions header
**	Automatically generated by Emperor
*/

#define ALL_REACTION_CLASSES
#define ALL_REACTION_MACROS

#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS

#define TapeDeckObject   IIntuition->NewObject(NULL, "tapedeck.gadget"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <proto/asl.h>
#include <proto/dos.h>
#include <proto/exec.h>
#include <proto/gadtools.h>
#include <proto/graphics.h>
#include <proto/icon.h>
#include <proto/intuition.h>
#include <proto/locale.h>
#include <proto/utility.h>
#include <proto/wb.h>
#include <proto/colorwheel.h>
#include <proto/datebrowser.h>
#include <libraries/resource.h>
#include <proto/texteditor.h>
#include <gadgets/colorwheel.h>
#include <gadgets/datebrowser.h>
#include <gadgets/gradientslider.h>
#include <gadgets/tapedeck.h>
#include <gadgets/texteditor.h>
#include <proto/texteditor.h>
#include <reaction/reaction.h>
#include <intuition/icclass.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <workbench/startup.h>

#include <devices/timer.h>

#include "globals.h"

#define VERSION "1"
#define REVISION "1"

#define PROGNAME "PassMaker"
#define DEVELOPER "George Sokianos"
#define DATE "10-Mar-2008"

#define Menu_Project1 65504
#define Menu_Information1 63488
#define Menu_Quit1 63520

