/*
**	Additional gadget handling functions
**	Automatically generated by Emperor
*/

#include "includes.h"

STRPTR inttostring(LONG Ep_IntInp)
{
	STRPTR Buffer;
	Buffer = IUtility->ASPrintf("%ld",Ep_IntInp);
	return(Buffer);
}


